openapi: 3.0.0
info:
  description: API 예제를 위한 샘플 API 명세서입니다.
  title: 샘플 API
  version: 1.0.0
servers:
- url: https://api.example.com/v1
paths:
  /users:
    get:
      description: 등록된 모든 사용자의 목록을 조회합니다.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: 사용자 목록 조회 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 잘못된 요청
      summary: 사용자 목록 조회
      x-accepts: application/json
components:
  schemas:
    User:
      example:
        name: John Doe
        id: 123
        email: john@example.com
      properties:
        id:
          description: 사용자 고유 ID
          example: 123
          type: integer
        name:
          description: 사용자 이름
          example: John Doe
          type: string
        email:
          description: 사용자 이메일
          example: john@example.com
          type: string
      required:
      - email
      - id
      - name
      type: object
    Error:
      properties:
        code:
          description: 에러 코드
          example: ERR_BAD_REQUEST
          type: string
        message:
          description: 에러 메시지
          example: 잘못된 요청입니다.
          type: string
      type: object

