openapi: 3.0.0
info:
  title: 샘플 API
  description: API 예제를 위한 샘플 API 명세서입니다.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /users:
    get:
      summary: 사용자 목록 조회
      description: 등록된 모든 사용자의 목록을 조회합니다.
      responses:
        '200':
          description: 사용자 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: 사용자 고유 ID
          example: 123
        name:
          type: string
          description: 사용자 이름
          example: John Doe
        email:
          type: string
          description: 사용자 이메일
          example: john@example.com
      required:
        - id
        - name
        - email

    Error:
      type: object
      properties:
        code:
          type: string
          description: 에러 코드
          example: "ERR_BAD_REQUEST"
        message:
          type: string
          description: 에러 메시지
          example: "잘못된 요청입니다."