logging:
  level:
    innim.fo.api.client:
      EventServiceClient: DEBUG

pixabay:
  api:
    url: https://pixabay.com/api/
    key: 25517874-3d73e6ca9886b99a1a9cba926

spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  sql:
    init:
      #      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
server:
  port: 20000

---

# local 프로파일 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    master:
      jdbc-url: jdbc:log4jdbc:h2:mem:masterdb;
      username: sa
      password:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 300000
        max-lifetime: 600000
        connection-timeout: 30000
        validation-timeout: 5000
    slave:
      jdbc-url: jdbc:log4jdbc:h2:mem:slavedb;
      username: sa
      password:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 300000
        max-lifetime: 600000
        connection-timeout: 30000
        validation-timeout: 5000
  h2:
    console:
      enabled: true
      path: /h2-console

---

# dev 프로파일 설정
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/yourdatabase
#    username: yourusername
#    password: yourpassword
#    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true